definitions:
  transfer.Transfer:
    properties:
      amount:
        type: number
      createdAt:
        type: string
      description:
        type: string
      fromWallet:
        type: integer
      id:
        type: integer
      toWallet:
        type: integer
    type: object
  user.User:
    properties:
      balance:
        type: number
      description:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      walletId:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/make-transfer:
    post:
      consumes:
      - application/json
      description: Makes a transfer to a specified walletId
      parameters:
      - description: X-Session-Token
        in: header
        name: X-Session-Token
        required: true
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/transfer.Transfer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/transfer.Transfer'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Makes a transfer to a specified walletId
      tags:
      - transfer
  /api/transfer/{id}:
    get:
      consumes:
      - application/json
      description: Get a transfer information by id
      parameters:
      - description: X-Session-Token
        in: header
        name: X-Session-Token
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/transfer.Transfer'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Get a transfer information by id
      tags:
      - transfer
  /api/user-transfers/{userId}:
    get:
      consumes:
      - application/json
      description: Get all transfers history of a user
      parameters:
      - description: X-Session-Token
        in: header
        name: X-Session-Token
        required: true
        type: string
      - description: userId
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/transfer.Transfer'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Get all transfers history of a user
      tags:
      - transfer
  /api/user/{id}:
    get:
      consumes:
      - application/json
      description: Get the a user's details and wallets information
      parameters:
      - description: X-Session-Token
        in: header
        name: X-Session-Token
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.User'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Get the a user's details and wallets information
      tags:
      - user
  /api/users:
    get:
      consumes:
      - application/json
      description: Get the list of all users and their wallets
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.User'
            type: array
      summary: Get the list of all users and their wallets
      tags:
      - user
swagger: "2.0"
